spring:
  application:
    name: pos-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pos-product-service
          uri: lb://pos-product
          predicates:
            - Path=/api/products/**
            - Method=GET
        - id: pos-cart-service
          uri: lb://pos-cart
          predicates:
            - Path=/api/cart/**
            - Method=[GET, POST, PUT, DELETE]
        - id: pos-order-service
          uri: lb://pos-order
          predicates:
            - Path=/api/order/**
            - Method=[GET, POST, PUT, DELETE]
        - id: pos-counter-service
          uri: lb://pos-counter
          predicates:
            - Path=/api/counter/**
            - Method=[POST]

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
